
  CREATE TABLE "S_UNIT" 
   (	"UNIT_ID" NUMBER NOT NULL ENABLE, 
	"UNIT_NAME" VARCHAR2(50 CHAR), 
	"UNIT_DESC" VARCHAR2(150), 
	 CONSTRAINT "S_UNIT_PK" PRIMARY KEY ("UNIT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "S_UNIT_UK" UNIQUE ("UNIT_NAME")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "S_UNIT_T" 
before
insert on "S_UNIT"
for each row
begin
    IF :NEW."UNIT_ID" IS NULL THEN
        SELECT "S_UNT_SEQ".nextval into :NEW."UNIT_ID" FROM SYS.DUAL;
    END IF;
end;
/
ALTER TRIGGER "S_UNIT_T" ENABLE;